### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by dieperdev** [Ralve-org/RabbitScout#1]
Could you add a Dockerfile to this project and possibly push it to ghcr? This would be a nice addon to my docker compose file.

**Comment by Talhazeb** [comment]
Sure, will be done it in a day or two.

**Comment by Talhazeb** [comment]
✅ Done! Docker support has been added with the following:

1. Added Dockerfile
2. Created docker-compose.yml for easy deployment
3. Set up GitHub Actions workflow for automatic publishing to GitHub Container Registry
4. Published the image to ghcr.io

You can now use RabbitScout in your docker-compose file:

```yaml
services:
  rabbitscout:
    image: ghcr.io/ralve-org/rabbitscout:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RABBITMQ_HOST=your-rabbitmq-host
      - NEXT_PUBLIC_RABBITMQ_PORT=15672
      - NEXT_PUBLIC_RABBITMQ_VHOST=/
      - RABBITMQ_USERNAME=your-username
      - RABBITMQ_PASSWORD=your-password
      - NEXT_PUBLIC_API_URL=http://localhost:3000
```

The image is publicly available at `ghcr.io/ralve-org/rabbitscout:latest`. Check out our [v1.0.0 release](https://github.com/Ralve-org/RabbitScout/releases/tag/v1.0.0) for more details and documentation.

Closes #1
